FROM node:16

ENV NODE_ENV=development
ENV DEBUG=true

WORKDIR /home/node/app

COPY package*.json ./

RUN ["npm", "install"]

EXPOSE 5000

COPY service.js /home/node/app/

RUN chown -R node:users /home/node/

USER node

CMD ["node", "service"]