FROM node:16

ENV NODE_ENV=development
ENV DEBUG=true

WORKDIR /home/node/app

COPY package.json .
COPY package-lock.json .

RUN ["npm", "install"]

EXPOSE 5007

COPY monitoring/monitorService.js /home/node/app/

RUN chown -R node:users /home/node/

USER node

CMD ["node", "monitorService"]